[env:atmega256rfr2]
platform = atmelavr
board = megaatmega2560
build_src_filter = +<main.cpp>
upload_protocol = xplainedpro
board_upload.require_upload_port = false
board_upload.extra_flags = -e

; Force ATmega256RFR2 target
board_build.mcu = atmega256rfr2
board_build.f_cpu = 8000000L

[env:atmega256rfr2_tx]
extends = env:atmega256rfr2
build_src_filter = +<transmitter.cpp>
build_flags = -DVEHICLE_ID=2